#!/bin/sh
#
# npm install eslint -g
# npm install babel-eslint -g
# npm install eslint-plugin-react -g

echo "\033[32mValidating Javascript\033[0m"

FILES=$(eslint -c .eslintrc.prod --ext .js --ext .jsx app | grep ".jsx\{0,1\}$")

if [[ "$FILES" = "" ]]; then
  echo "\033[32mESLint validation passed!\033[0m"
  exit 0
else
  for FILE in $FILES
  do
    eslint -c .eslintrc.prod --ext .js --ext .jsx "$FILE"
  done
  echo "\033[91mESLint validation failed!\033[0m"
  exit 1
fi

